---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Arabic_FriendlyGuy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Friendly Guy"
  description: "A natural and friendly adult male Arabic voice."
  provider_data:
    voice_id: "Arabic_FriendlyGuy"
    voice_type: "system"
