---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Cantonese_CuteGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Cute Girl"
  description: "A soothing and cute young adult female voice in Cantonese."
  provider_data:
    voice_id: "Cantonese_CuteGirl"
    voice_type: "system"
    model: speech-2.6-turbo
