---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Cantonese_ProfessionalHost（M)"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Professional Male Host"
  description: "A neutral and professional adult male host in Cantonese."
  provider_data:
    voice_id: "Cantonese_ProfessionalHost（M)"
    voice_type: "system"
