---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Cantonese_PlayfulMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Playful Man"
  description: "A soulful and playful adult male voice in Cantonese."
  provider_data:
    voice_id: "Cantonese_PlayfulMan"
    voice_type: "system"
    model: "speech-2.6-turbo"
