---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Cantonese_GentleLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Gentle Lady"
  description: "A calm and gentle adult female voice in Cantonese."
  provider_data:
    voice_id: "Cantonese_GentleLady"
    voice_type: "system"
    model: "speech-2.6-turbo"
