---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Chinese (Mandarin)_BashfulGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Bashful Girl"
  description: "A bashful and shy female youth voice in Standard Mandarin."
  provider_data:
    voice_id: "Chinese (Mandarin)_BashfulGirl"
    voice_type: "system"
