---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Chinese (Mandarin)_Sincere_Adult"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Sincere Adult"
  description: "A sincere and encouraging adult male voice in Standard Mandarin."
  provider_data:
    voice_id: "Chinese (Mandarin)_Sincere_Adult"
    voice_type: "system"
