---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Chinese (Mandarin)_Wise_Women"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Wise Women"
  description: "A lyrical and wise middle-aged female voice in Standard Mandarin."
  provider_data:
    voice_id: "Chinese (Mandarin)_Wise_Women"
    voice_type: "system"
