---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Chinese (Mandarin)_Unrestrained_Young_Man"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Unrestrained Young Man"
  description: "An unrestrained and free-spirited adult male voice in Standard Mandarin."
  provider_data:
    voice_id: "Chinese (Mandarin)_Unrestrained_Young_Man"
    voice_type: "system"
    model: "speech-2.6-turbo"
