---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Chinese (Mandarin)_Gentleman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Gentleman"
  description: "A magnetic and charismatic adult male gentleman in Standard Mandarin."
  provider_data:
    voice_id: "Chinese (Mandarin)_Gentleman"
    voice_type: "system"
