---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Chinese (Mandarin)_Warm_HeartedGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Warm-hearted Girl"
  description: "A warm-hearted and caring adult female voice in Standard Mandarin."
  provider_data:
    voice_id: "Chinese (Mandarin)_Warm_HeartedGirl"
    voice_type: "system"
