---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Chinese (Mandarin)_Stubborn_Friend"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Stubborn Friend"
  description: "An uninhibited and stubborn adult male friend's voice in Standard Mandarin."
  provider_data:
    voice_id: "Chinese (Mandarin)_Stubborn_Friend"
    voice_type: "system"
