---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Chinese (Mandarin)_Lyrical_Voice"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Lyrical Voice"
  description: "A mellow and lyrical adult male voice in Standard Mandarin, smooth and expressive."
  provider_data:
    voice_id: "Chinese (Mandarin)_Lyrical_Voice"
    voice_type: "system"
    model: "speech-2.6-turbo"
