---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Chinese (Mandarin)_Straightforward_Boy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Straightforward Boy"
  description: "A thoughtful and straightforward young adult male voice in Standard Mandarin."
  provider_data:
    voice_id: "Chinese (Mandarin)_Straightforward_Boy"
    voice_type: "system"
    model: speech-2.6-turbo
