---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Chinese (Mandarin)_Warm_Bestie"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Warm Bestie"
  description: "A warm and crisp adult female \"bestie\" voice in Standard Mandarin, friendly and clear."
  provider_data:
    voice_id: "Chinese (Mandarin)_Warm_Bestie"
    voice_type: "system"
