---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Chinese (Mandarin)_Mature_Woman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Mature Woman"
  description: "A charming and mature adult female voice in Standard Mandarin."
  provider_data:
    voice_id: "Chinese (Mandarin)_Mature_Woman"
    voice_type: "system"
