---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:czech_male_1_v1"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Assured Presenter"
  description: "A serious and assured young adult male presenter's voice in Czech."
  provider_data:
    voice_id: "czech_male_1_v1"
    voice_type: "system"
    model: "speech-2.6-turbo"
