---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Dutch_bossy_leader"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Bossy leader"
  description: "A serious and bossy adult male leader's voice in Dutch."
  provider_data:
    voice_id: "Dutch_bossy_leader"
    voice_type: "system"
    model: speech-2.6-turbo
