---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:English_Strong-WilledBoy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Strong-Willed Boy"
  description: "A mature-sounding and strong-willed young adult male with a British accent, showing determination beyond his years."
  provider_data:
    voice_id: "English_Strong-WilledBoy"
    voice_type: "system"
