---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:English_Jovialman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Jovial Man"
  description: "A jovial and mature middle-aged male voice with a general American accent, cheerful and good-natured."
  provider_data:
    voice_id: "English_Jovialman"
    voice_type: "system"
