---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:English_Upbeat_Woman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Upbeat Woman"
  description: "An upbeat and bright adult female voice with a general American accent, perfect for energetic and positive messaging."
  provider_data:
    voice_id: "English_Upbeat_Woman"
    voice_type: "system"
