---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:English_DecentYoungMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Decent Young Man"
  description: "A decent and respectable adult male voice with a British accent, sounding polite and well-mannered."
  provider_data:
    voice_id: "English_DecentYoungMan"
    voice_type: "system"
