---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:English_radiant_girl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Radiant Girl"
  description: "A radiant and lively young adult female voice with a general American accent, full of energy and brightness."
  provider_data:
    voice_id: "English_radiant_girl"
    voice_type: "system"
    model: "speech-2.6-turbo"
