---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:English_PlayfulGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Playful Girl"
  description: "A playful female youth voice with a general American accent, ideal for cartoons and children's entertainment."
  provider_data:
    voice_id: "English_PlayfulGirl"
    voice_type: "system"
    model: speech-2.6-turbo
