---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:English_CalmWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Calm Woman"
  description: "A calm and soothing adult female voice with a general American accent, excellent for audiobooks and meditation guides."
  provider_data:
    voice_id: "English_CalmWoman"
    voice_type: "system"
