---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:English_ManWithDeepVoice"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Man With Deep Voice"
  description: "An adult male with a deep, commanding voice and a general American accent, projecting authority and strength."
  provider_data:
    voice_id: "English_ManWithDeepVoice"
    voice_type: "system"
