---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:English_Trustworth_Man"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Trustworthy Man"
  description: "A trustworthy and resonant adult male voice with a general American accent, conveying sincerity and reliability."
  provider_data:
    voice_id: "English_Trustworth_Man"
    voice_type: "system"
    model: "speech-2.6-turbo"
