---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:English_Whispering_girl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Whispering girl"
  provider_data:
    voice_id: "English_Whispering_girl"
    voice_type: "system"
