---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:English_SereneWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Serene Woman"
  description: "A serene and friendly young adult female voice with a general American accent, calm and welcoming."
  provider_data:
    voice_id: "English_SereneWoman"
    voice_type: "system"
