---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:English_BossyLeader"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Bossy Leader"
  description: "A bossy adult male leader with a general American accent, speaking unconcernedly with an air of command."
  provider_data:
    voice_id: "English_BossyLeader"
    voice_type: "system"
