---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:English_LovelyGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Lovely Girl"
  description: "A lovely and sweet female youth voice with a British accent, full of charm and innocence."
  provider_data:
    voice_id: "English_LovelyGirl"
    voice_type: "system"
    model: "speech-2.6-turbo"
