---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:English_Gentle-voiced_man"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Gentle-voiced Man"
  description: "A gentle and resonant adult male voice with a general American accent, warm and reassuring."
  provider_data:
    voice_id: "English_Gentle-voiced_man"
    voice_type: "system"
