---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:English_ConfidentWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Confident Woman"
  description: "A confident and firm young adult female voice with a general American accent, assertive and clear."
  provider_data:
    voice_id: "English_ConfidentWoman"
    voice_type: "system"
    model: speech-2.6-turbo
