---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:finnish_female_4_v1"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Assetive Woman"
  description: "A determined and assertive adult female voice in Finnish."
  provider_data:
    voice_id: "finnish_female_4_v1"
    voice_type: "system"
