---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:finnish_male_3_v1"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Upbeat Man"
  description: "An energetic and upbeat young adult female voice in Finnish."
  provider_data:
    voice_id: "finnish_male_3_v1"
    voice_type: "system"
