---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:French_MovieLeadFemale"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Movie Lead Female"
  description: "A cinematic young adult female lead voice in French, perfect for film."
  provider_data:
    voice_id: "French_MovieLeadFemale"
    voice_type: "system"
