---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:French_MovieLeadFemale"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Movie Lead Female"
  description: "A cinematic young adult female lead voice in French, perfect for film."
  provider_data:
    voice_id: "French_MovieLeadFemale"
    voice_type: "system"
    model: speech-2.6-turbo
