---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:German_FriendlyMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Friendly Man"
  description: "A sincere and friendly middle-aged male voice in German."
  provider_data:
    voice_id: "German_FriendlyMan"
    voice_type: "system"
