---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:greek_male_1a_v1"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Thoughtful Mentor"
  description: "An intellectual and thoughtful adult male mentor's voice in Greek."
  provider_data:
    voice_id: "greek_male_1a_v1"
    voice_type: "system"
