---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Greek_female_2_sample3"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Girl Next Door"
  description: "A cheerful young adult \"girl next door\" voice in Greek."
  provider_data:
    voice_id: "Greek_female_2_sample3"
    voice_type: "system"
    model: speech-2.6-turbo
