---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Greek_female_1_sample1"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Gentle Lady"
  description: "A gentle adult lady's voice in Greek."
  provider_data:
    voice_id: "Greek_female_1_sample1"
    voice_type: "system"
