---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Indonesian_ConfidentWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Confident Woman"
  description: "An assertive and confident young adult female voice in Indonesian."
  provider_data:
    voice_id: "Indonesian_ConfidentWoman"
    voice_type: "system"
