---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Indonesian_CharmingGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Charming Girl"
  description: "An alluring and charming adult female voice in Indonesian."
  provider_data:
    voice_id: "Indonesian_CharmingGirl"
    voice_type: "system"
