---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Indonesian_CaringMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Caring Man"
  description: "A compassionate and caring young adult male voice in Indonesian."
  provider_data:
    voice_id: "Indonesian_CaringMan"
    voice_type: "system"
