---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Italian_BraveHeroine"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Brave Heroine"
  description: "A calm and brave middle-aged female heroine's voice in Italian."
  provider_data:
    voice_id: "Italian_BraveHeroine"
    voice_type: "system"
