---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Italian_WanderingSorcerer"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Wandering Sorcerer"
  description: "A ruthless adult female wandering sorcerer's voice in Italian."
  provider_data:
    voice_id: "Italian_WanderingSorcerer"
    voice_type: "system"
