---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Italian_DiligentLeader"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Diligent Leader"
  description: "A calm and diligent adult female leader's voice in Italian."
  provider_data:
    voice_id: "Italian_DiligentLeader"
    voice_type: "system"
    model: speech-2.6-turbo
