---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Italian_Narrator"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Narrator"
  description: "A classic middle-aged male narrator voice in Italian."
  provider_data:
    voice_id: "Italian_Narrator"
    voice_type: "system"
