---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Japanese_SportyStudent"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Sporty Student"
  description: "An inviting and sporty adult male student's voice in Standard Japanese."
  provider_data:
    voice_id: "Japanese_SportyStudent"
    voice_type: "system"
    model: speech-2.6-turbo
