---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Japanese_OptimisticYouth"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Optimistic Youth"
  description: "A cheerful and optimistic adult male youth's voice in Japanese."
  provider_data:
    voice_id: "Japanese_OptimisticYouth"
    voice_type: "system"
    model: speech-2.6-turbo
