---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Japanese_DominantMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Dominant Man"
  description: "A mature and dominant middle-aged male voice in Japanese."
  provider_data:
    voice_id: "Japanese_DominantMan"
    voice_type: "system"
