---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Japanese_DependableWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Dependable Woman"
  description: "A steady and dependable adult female voice in Japanese."
  provider_data:
    voice_id: "Japanese_DependableWoman"
    voice_type: "system"
    model: speech-2.6-turbo
