---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Japanese_SeriousCommander"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Serious Commander"
  description: "A serious and reliable adult male commander's voice in Japanese."
  provider_data:
    voice_id: "Japanese_SeriousCommander"
    voice_type: "system"
