---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Japanese_IntellectualSenior"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Intellectual Senior"
  description: "A mature and intellectual young adult male voice in Japanese, sounding older than his age."
  provider_data:
    voice_id: "Japanese_IntellectualSenior"
    voice_type: "system"
