---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Japanese_KindLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Kind Lady"
  description: "A charming and kind adult female voice in Japanese."
  provider_data:
    voice_id: "Japanese_KindLady"
    voice_type: "system"
    model: "speech-2.6-turbo"
