---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Japanese_CalmLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Calm Lady"
  description: "A calm and charming adult female voice in Japanese."
  provider_data:
    voice_id: "Japanese_CalmLady"
    voice_type: "system"
    model: speech-2.6-turbo
