---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Japanese_LoyalKnight"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Loyal Knight"
  description: "A youthful and loyal adult male knight's voice in Japanese."
  provider_data:
    voice_id: "Japanese_LoyalKnight"
    voice_type: "system"
