---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Korean_SoothingLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Soothing Lady"
  description: "An alluring and soothing middle-aged female voice in Standard Korean."
  provider_data:
    voice_id: "Korean_SoothingLady"
    voice_type: "system"
