---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Korean_ChildhoodFriendGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Childhood Friend Girl"
  description: "A polite and reserved young adult female \"childhood friend\" voice in Standard Korean."
  provider_data:
    voice_id: "Korean_ChildhoodFriendGirl"
    voice_type: "system"
