---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Korean_QuirkyGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Quirky Girl"
  description: "An adorable and quirky female youth voice in Standard Korean."
  provider_data:
    voice_id: "Korean_QuirkyGirl"
    voice_type: "system"
