---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Korean_BraveFemaleWarrior"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Brave Female Warrior"
  description: "A resolute young adult brave female warrior's voice in Standard Korean."
  provider_data:
    voice_id: "Korean_BraveFemaleWarrior"
    voice_type: "system"
    model: speech-2.6-turbo
