---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Korean_ColdGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Cold Girl"
  description: "An aloof and cold adult female voice in Standard Korean."
  provider_data:
    voice_id: "Korean_ColdGirl"
    voice_type: "system"
