---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Korean_MatureLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Mature Lady"
  description: "A refined and elegant mature middle-aged lady's voice in Standard Korean."
  provider_data:
    voice_id: "Korean_MatureLady"
    voice_type: "system"
