---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Korean_ShyGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Shy Girl"
  description: "A timid and introverted young adult female voice in Standard Korean."
  provider_data:
    voice_id: "Korean_ShyGirl"
    voice_type: "system"
