---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Korean_InnocentBoy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Innocent Boy"
  description: "A naive and pure young adult male \"innocent boy\" voice in Standard Korean."
  provider_data:
    voice_id: "Korean_InnocentBoy"
    voice_type: "system"
