---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Korean_EnthusiasticTeen"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Enthusiastic Teen"
  description: "A passionate and lively young adult male teen's voice in Standard Korean."
  provider_data:
    voice_id: "Korean_EnthusiasticTeen"
    voice_type: "system"
    model: speech-2.6-turbo
