---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Korean_BraveAdventurer"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Brave Adventurer"
  description: "A playful and adventurous adult female brave adventurer's voice in Standard Korean."
  provider_data:
    voice_id: "Korean_BraveAdventurer"
    voice_type: "system"
