---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Korean_CharmingSister"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Charming Sister"
  description: "A seductive middle-aged \"charming sister\" voice in Standard Korean."
  provider_data:
    voice_id: "Korean_CharmingSister"
    voice_type: "system"
