---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Korean_CockyGuy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Cocky Guy"
  description: "A playful and mischievous young adult cocky guy's voice in Standard Korean."
  provider_data:
    voice_id: "Korean_CockyGuy"
    voice_type: "system"
