---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Polish_female_2_sample3"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Casual Woman"
  description: "A neutral and casual adult female voice in Polish."
  provider_data:
    voice_id: "Polish_female_2_sample3"
    voice_type: "system"
