---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Portuguese_RationalMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Rational Man"
  description: "A thoughtful and rational adult male voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_RationalMan"
    voice_type: "system"
