---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_SmartYoungGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Smart Young Girl"
  description: "An intelligent young female girl's voice in Standard Portuguese, sharp and clear."
  provider_data:
    voice_id: "Portuguese_SmartYoungGirl"
    voice_type: "system"
