---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_BossyLeader"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Bossy Leader"
  description: "A calm and formal adult male bossy leader's voice in Portuguese."
  provider_data:
    voice_id: "Portuguese_BossyLeader"
    voice_type: "system"
