---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_PlayfulSpirit"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Playful Spirit"
  description: "An animated and playful young adult female spirit's voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_PlayfulSpirit"
    voice_type: "system"
