---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Portuguese_SentimentalLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Sentimental Lady"
  description: "An elegant and sentimental young adult female voice in Portuguese."
  provider_data:
    voice_id: "Portuguese_SentimentalLady"
    voice_type: "system"
    model: "speech-2.6-turbo"
