---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_Steadymentor"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Steady Mentor"
  description: "An arrogant yet steady young adult male mentor's voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_Steadymentor"
    voice_type: "system"
