---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Portuguese_ElegantGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Elegant Girl"
  description: "A dramatic and elegant young adult female voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_ElegantGirl"
    voice_type: "system"
    model: "speech-2.6-turbo"
