---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_ThoughtfulMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Thoughtful Man"
  description: "A gentle and thoughtful young adult male voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_ThoughtfulMan"
    voice_type: "system"
