---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_ReservedYoungMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Reserved Young Man"
  description: "A cold and calm reserved young adult male voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_ReservedYoungMan"
    voice_type: "system"
