---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_ConfidentWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Confident Woman"
  description: "A clear and firm young adult confident woman's voice in Portuguese."
  provider_data:
    voice_id: "Portuguese_ConfidentWoman"
    voice_type: "system"
