---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Portuguese_SensibleManager"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Sensible Manager"
  description: "A charismatic and sensible middle-aged male manager's voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_SensibleManager"
    voice_type: "system"
