---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Portuguese_HumorousElder"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Humorous Elder"
  description: "A wacky and humorous middle-aged male elder's voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_HumorousElder"
    voice_type: "system"
    model: "speech-2.6-turbo"
