---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_InspiringLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Inspiring Lady"
  description: "A commanding and inspiring young adult female voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_InspiringLady"
    voice_type: "system"
