---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_NaughtySchoolgirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Naughty Schoolgirl"
  description: "An inviting and naughty young adult female schoolgirl's voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_NaughtySchoolgirl"
    voice_type: "system"
