---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_CharmingLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Charming Lady"
  provider_data:
    voice_id: "Portuguese_CharmingLady"
    voice_type: "system"
