---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_SereneElder"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Serene Elder"
  description: "A reflective and serene middle-aged male elder's voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_SereneElder"
    voice_type: "system"
