---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_Jovialman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Jovial Man"
  description: "A jovial and laughing middle-aged male voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_Jovialman"
    voice_type: "system"
