---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_Pompouslady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Pompous lady"
  description: "A pompous young adult female cartoon-style voice in Standard Portuguese, full of personality."
  provider_data:
    voice_id: "Portuguese_Pompouslady"
    voice_type: "system"
