---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_EnergeticBoy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Energetic Boy"
  description: "A cheerful and energetic young adult male voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_EnergeticBoy"
    voice_type: "system"
