---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_GentleTeacher"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Gentle Teacher"
  description: "A mild and gentle adult male teacher's voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_GentleTeacher"
    voice_type: "system"
