---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_PowerfulVeteran"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Powerful Veteran"
  description: "A strong and powerful middle-aged male veteran's voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_PowerfulVeteran"
    voice_type: "system"
