---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Portuguese_FragileBoy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Fragile Boy"
  description: "A gentle and fragile young adult male voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_FragileBoy"
    voice_type: "system"
    model: speech-2.6-turbo
