---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Portuguese_TheatricalActor"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Theatrical Actor"
  description: "An animated middle-aged male theatrical actor's voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_TheatricalActor"
    voice_type: "system"
