---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Portuguese_Strong-WilledBoy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Strong-willed Boy"
  description: "A mature and strong-willed young adult male voice in Portuguese."
  provider_data:
    voice_id: "Portuguese_Strong-WilledBoy"
    voice_type: "system"
