---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_Dramatist"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Dramatist"
  description: "A quirky middle-aged male dramatist's voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_Dramatist"
    voice_type: "system"
