---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Portuguese_ElegantGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Elegant Girl"
  description: "A dramatic and elegant young adult female voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_ElegantGirl"
    voice_type: "system"
