---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Portuguese_ToughBoss"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Tough Boss"
  description: "A mature and tough middle-aged female boss's voice in Standard Portuguese."
  provider_data:
    voice_id: "Portuguese_ToughBoss"
    voice_type: "system"
    model: "speech-2.6-turbo"
