---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Robot_Armor"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Robot Armor"
  description: "An electronic, robotic adult male voice, suitable for sci-fi or futuristic content in Standard Mandarin."
  provider_data:
    voice_id: "Robot_Armor"
    voice_type: "system"
