---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Romanian_female_1_sample4"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Optimistic Youth"
  description: "A cheerful and optimistic adult female youth's voice in Romanian."
  provider_data:
    voice_id: "Romanian_female_1_sample4"
    voice_type: "system"
    model: "speech-2.6-turbo"
