---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Romanian_male_2_sample1"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Energetic Youth"
  description: "An energetic adult male youth's voice in Romanian."
  provider_data:
    voice_id: "Romanian_male_2_sample1"
    voice_type: "system"
