---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Romanian_female_1_sample4"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Optimistic Youth"
  description: "A cheerful and optimistic adult female youth's voice in Romanian."
  provider_data:
    voice_id: "Romanian_female_1_sample4"
    voice_type: "system"
