---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Romanian_male_1_sample2"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Reliable Man"
  description: "A neutral and reliable adult male voice in Romanian."
  provider_data:
    voice_id: "Romanian_male_1_sample2"
    voice_type: "system"
    model: "speech-2.6-turbo"
