---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Romanian_female_2_sample1"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Gentle Woman"
  description: "A gentle adult female voice in Romanian."
  provider_data:
    voice_id: "Romanian_female_2_sample1"
    voice_type: "system"
