---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Russian_BrightHeroine"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Bright Queen"
  description: "An arrogant and bright adult queen's voice in Standard Russian."
  provider_data:
    voice_id: "Russian_BrightHeroine"
    voice_type: "system"
    model: speech-2.6-turbo
