---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Russian_CrazyQueen"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Crazy Girl"
  description: "An energetic adult female \"crazy girl\" voice in Standard Russian, wild and unpredictable."
  provider_data:
    voice_id: "Russian_CrazyQueen"
    voice_type: "system"
    model: "speech-2.6-turbo"
