---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Russian_Bad-temperedBoy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Bad-tempered Boy"
  description: "A charming adult male \"bad-tempered boy\" voice in Standard Russian."
  provider_data:
    voice_id: "Russian_Bad-temperedBoy"
    voice_type: "system"
