---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Spanish_Ghost"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Ghost"
  description: "A raspy adult male ghost's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_Ghost"
    voice_type: "system"
