---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_ThoughtfulLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Thoughtful Lady"
  description: "A worried and thoughtful adult lady's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_ThoughtfulLady"
    voice_type: "system"
    model: "speech-2.6-turbo"
