---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Spanish_AngryMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Angry Man"
  description: "An intense young adult male voice in Standard Spanish, conveying anger."
  provider_data:
    voice_id: "Spanish_AngryMan"
    voice_type: "system"
