---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_Strong-WilledBoy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Strong-willed Boy"
  description: "A mature and strong-willed adult male voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_Strong-WilledBoy"
    voice_type: "system"
    model: speech-2.6-turbo
