---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_ReservedYoungMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Reserved Young Man"
  description: "A tranquil and reserved young adult male voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_ReservedYoungMan"
    voice_type: "system"
    model: "speech-2.6-turbo"
