---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_SophisticatedLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Sophisticated Lady"
  description: "A refined and sophisticated adult lady's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_SophisticatedLady"
    voice_type: "system"
    model: speech-2.6-turbo
