---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_CompellingGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Compelling Girl"
  description: "A persuasive and compelling young adult female voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_CompellingGirl"
    voice_type: "system"
