---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Spanish_StrictBoss"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Strict Boss"
  description: "A commanding and strict young adult female boss's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_StrictBoss"
    voice_type: "system"
