---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_SantaClaus"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Santa Claus"
  description: "A joyful senior male Santa Claus voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_SantaClaus"
    voice_type: "system"
