---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_RomanticHusband"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Romantic Husband"
  description: "An emotional middle-aged male romantic husband's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_RomanticHusband"
    voice_type: "system"
