---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Spanish_HumorousElder"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Humorous Elder"
  description: "An eccentric and humorous senior male elder's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_HumorousElder"
    voice_type: "system"
