---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_AssertiveQueen"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Assertive Queen"
  description: "A firm and assertive young adult queen's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_AssertiveQueen"
    voice_type: "system"
