---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_EnergeticBoy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Energetic Boy"
  description: "A cheerful and energetic young adult male voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_EnergeticBoy"
    voice_type: "system"
    model: "speech-2.6-turbo"
