---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_PassionateWarrior"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Passionate Warrior"
  description: "An energetic and passionate young adult male warrior's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_PassionateWarrior"
    voice_type: "system"
    model: speech-2.6-turbo
