---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Spanish_BossyLeader"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Bossy Leader"
  description: "A businesslike and bossy adult male leader's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_BossyLeader"
    voice_type: "system"
