---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_Steadymentor"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Steady Mentor"
  description: "An arrogant yet steady young adult male mentor's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_Steadymentor"
    voice_type: "system"
