---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Spanish_Fussyhostess"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Fussy hostess"
  description: "An intense and fussy middle-aged female hostess's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_Fussyhostess"
    voice_type: "system"
