---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Spanish_DeterminedManager"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Determined Manager"
  description: "A businesslike and determined middle-aged female manager's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_DeterminedManager"
    voice_type: "system"
