---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Spanish_FrankLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Frank Lady"
  description: "An agitated and frank adult lady's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_FrankLady"
    voice_type: "system"
