---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_Rudolph"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Rudolph"
  description: "A naive young adult male voice in the style of Rudolph in Standard Spanish."
  provider_data:
    voice_id: "Spanish_Rudolph"
    voice_type: "system"
    model: speech-2.6-turbo
