---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Spanish_SensibleManager"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Sensible Manager"
  description: "A charismatic and sensible adult male manager's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_SensibleManager"
    voice_type: "system"
