---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Spanish_AnimeCharacter"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Anime Character"
  description: "An animated middle-aged female voice in Standard Spanish, suitable for anime characters."
  provider_data:
    voice_id: "Spanish_AnimeCharacter"
    voice_type: "system"
