---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Spanish_Kind-heartedGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Kind-hearted Girl"
  description: "A bright and kind-hearted young adult female voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_Kind-heartedGirl"
    voice_type: "system"
    model: speech-2.6-turbo
