---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Spanish_CaringGirlfriend"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Caring Girlfriend"
  description: "A dreamy adult female caring girlfriend's voice in Standard Spanish."
  provider_data:
    voice_id: "Spanish_CaringGirlfriend"
    voice_type: "system"
