---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Thai_male_1_sample8"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Serene Man"
  description: "A magnetic and serene adult male voice in Thai."
  provider_data:
    voice_id: "Thai_male_1_sample8"
    voice_type: "system"
    model: speech-2.6-turbo
