---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Thai_male_2_sample2"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Friendly Man"
  description: "A lively and friendly adult male voice in Thai."
  provider_data:
    voice_id: "Thai_male_2_sample2"
    voice_type: "system"
