---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-global:Thai_male_1_sample8"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-global"
  name: "Serene Man"
  description: "A magnetic and serene adult male voice in Thai."
  provider_data:
    voice_id: "Thai_male_1_sample8"
    voice_type: "system"
