---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-global:Ukrainian_WiseScholar"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-global"
  display_name: "Wise Scholar"
  description: "A conversational young adult male wise scholar's voice in Ukrainian."
  provider_data:
    voice_id: "Ukrainian_WiseScholar"
    voice_type: "system"
    model: speech-2.6-turbo
