---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Arabic_FriendlyGuy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Friendly Guy"
  description: "一位沉稳友好的青年男性阿拉伯语声音。"
  provider_data:
    voice_id: "Arabic_FriendlyGuy"
    voice_type: "system"
    model: "speech-2.6-turbo"
