---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Arabic_CalmWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Calm Woman"
  description: "一位宁静的青年女性阿拉伯语声音。"
  provider_data:
    voice_id: "Arabic_CalmWoman"
    voice_type: "system"
