---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:badao_shaoye"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "霸道少爷"
  provider_data:
    voice_id: "badao_shaoye"
    voice_type: "system"
