---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Cantonese_KindWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "善良女声"
  description: "一位亲切善良的青年女性粤语声音。"
  provider_data:
    voice_id: "Cantonese_KindWoman"
    voice_type: "system"
    model: "speech-2.6-turbo"
