---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Cantonese_CuteGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "可爱女孩"
  description: "一位柔和可爱的青年女性粤语声音。"
  provider_data:
    voice_id: "Cantonese_CuteGirl"
    voice_type: "system"
