---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Charming_Santa"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Charming Santa"
  provider_data:
    voice_id: "Charming_Santa"
    voice_type: "system"
    model: "speech-2.6-turbo"
