---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Chinese (Mandarin)_Radio_Host"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "电台男主播"
  description: "一位富有诗意的青年男性电台主播声音，标准普通话，声音流畅引人入胜。"
  provider_data:
    voice_id: "Chinese (Mandarin)_Radio_Host"
    voice_type: "system"
    model: speech-2.6-turbo
