---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Chinese (Mandarin)_Warm_Girl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "温暖少女"
  description: "一位温柔温暖的少年女声，标准普通话。"
  provider_data:
    voice_id: "Chinese (Mandarin)_Warm_Girl"
    voice_type: "system"
    model: speech-2.6-turbo
