---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:chunzhen_xuedi"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "纯真学弟"
  provider_data:
    voice_id: "chunzhen_xuedi"
    voice_type: "system"
