---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:clever_boy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "聪明男童"
  provider_data:
    voice_id: "clever_boy"
    voice_type: "system"
    model: "speech-2.6-turbo"
