---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Cute_Elf"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Cute Elf"
  provider_data:
    voice_id: "Cute_Elf"
    voice_type: "system"
    model: speech-2.6-turbo
