---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:diadia_xuemei"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "嗲嗲学妹"
  provider_data:
    voice_id: "diadia_xuemei"
    voice_type: "system"
    model: "speech-2.6-turbo"
