---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:English_Whispering_girl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Whispering girl"
  description: "一位青年女性的轻柔耳语声，带通用美式口音，非常适合ASMR内容。"
  provider_data:
    voice_id: "English_Whispering_girl"
    voice_type: "system"
    model: "speech-2.6-turbo"
