---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:English_Trustworthy_Man"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Trustworthy Man"
  description: "一位值得信赖、富有磁性的青年男性声音，带通用美式口音。"
  provider_data:
    voice_id: "English_Trustworthy_Man"
    voice_type: "system"
    model: "speech-2.6-turbo"
