---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:English_Gentle-voiced_man"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Gentle-voiced man"
  description: "一位声音温柔、富有磁性的青年男性，带通用美式口音。"
  provider_data:
    voice_id: "English_Gentle-voiced_man"
    voice_type: "system"
