---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:female-chengshu-jingpin"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "成熟女性音色-beta"
  provider_data:
    voice_id: "female-chengshu-jingpin"
    voice_type: "system"
