---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:French_Male_Speech_New"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Level-Headed Man"
  description: "一位理智的青年男性法语声音。"
  provider_data:
    voice_id: "French_Male_Speech_New"
    voice_type: "system"
    model: "speech-2.6-turbo"
