---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:French_FemaleAnchor"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Female Anchor"
  description: "一位成熟的女性法语主播声音。"
  provider_data:
    voice_id: "French_FemaleAnchor"
    voice_type: "system"
