---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:German_PlayfulMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Playful Man"
  description: "一位活泼的青年男性德语声音。"
  provider_data:
    voice_id: "German_PlayfulMan"
    voice_type: "system"
