---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:German_FriendlyMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Friendly Man"
  description: "一位真诚友好的中年男性德语声音。"
  provider_data:
    voice_id: "German_FriendlyMan"
    voice_type: "system"
