---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Indonesian_ConfidentWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Confident Woman"
  description: "一位自信的青年女性印尼语声音。"
  provider_data:
    voice_id: "Indonesian_ConfidentWoman"
    voice_type: "system"
    model: "speech-2.6-turbo"
