---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Indonesian_GentleGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Gentle Girl"
  description: "一位柔和的青年女性印尼语声音。"
  provider_data:
    voice_id: "Indonesian_GentleGirl"
    voice_type: "system"
