---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Indonesian_BossyLeader"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Bossy Leader"
  description: "一位权威的青年男性领导者声音，印尼语。"
  provider_data:
    voice_id: "Indonesian_BossyLeader"
    voice_type: "system"
