---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Indonesian_DeterminedBoy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Determined Boy"
  description: "一位坚定的青年男性印尼语声音。"
  provider_data:
    voice_id: "Indonesian_DeterminedBoy"
    voice_type: "system"
    model: speech-2.6-turbo
