---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Indonesian_CharmingGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Charming Girl"
  description: "一位迷人的青年女性印尼语声音。"
  provider_data:
    voice_id: "Indonesian_CharmingGirl"
    voice_type: "system"
    model: speech-2.6-turbo
