---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Indonesian_SweetGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Sweet Girl"
  description: "一位甜美可爱的青年女性印尼语声音。"
  provider_data:
    voice_id: "Indonesian_SweetGirl"
    voice_type: "system"
