---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Italian_Narrator"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Narrator"
  description: "一位适合叙述的中年男性意大利语声音。"
  provider_data:
    voice_id: "Italian_Narrator"
    voice_type: "system"
    model: speech-2.6-turbo
