---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Italian_BraveHeroine"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Brave Heroine"
  description: "一位沉稳勇敢的中年女英雄声音，意大利语。"
  provider_data:
    voice_id: "Italian_BraveHeroine"
    voice_type: "system"
