---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Italian_DiligentLeader"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Diligent Leader"
  description: "一位冷静勤奋的青年女性领导者声音，意大利语。"
  provider_data:
    voice_id: "Italian_DiligentLeader"
    voice_type: "system"
