---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Japanese_DominantMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Dominant Man"
  description: "一位成熟强势的中年男性声音，日语。"
  provider_data:
    voice_id: "Japanese_DominantMan"
    voice_type: "system"
