---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Japanese_LoyalKnight"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Loyal Knight"
  description: "一位年轻忠诚的青年男性骑士声音，日语。"
  provider_data:
    voice_id: "Japanese_LoyalKnight"
    voice_type: "system"
