---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Japanese_GentleButler"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Gentle Butler"
  description: "一位迷人温柔的青年男性管家声音，日语。"
  provider_data:
    voice_id: "Japanese_GentleButler"
    voice_type: "system"
