---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Japanese_GracefulMaiden"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Graceful Maiden"
  description: "一位甜美优雅的青年少女声音，日语。"
  provider_data:
    voice_id: "Japanese_GracefulMaiden"
    voice_type: "system"
