---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Japanese_SportyStudent"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Sporty Student"
  description: "一位亲切运动的青年男性学生声音，日语。"
  provider_data:
    voice_id: "Japanese_SportyStudent"
    voice_type: "system"
    model: speech-2.6-turbo
