---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Japanese_DecisivePrincess"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Decisive Princess"
  description: "一位坚定果断的青年公主声音，日语。"
  provider_data:
    voice_id: "Japanese_DecisivePrincess"
    voice_type: "system"
    model: speech-2.6-turbo
