---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Japanese_CalmLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Calm Lady"
  description: "一位沉静迷人的青年女性声音，日语。"
  provider_data:
    voice_id: "Japanese_CalmLady"
    voice_type: "system"
