---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Japanese_SeriousCommander"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Serious Commander"
  description: "一位严肃可靠的青年男性指挥官声音，日语。"
  provider_data:
    voice_id: "Japanese_SeriousCommander"
    voice_type: "system"
