---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Korean_EnchantingSister"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Enchanting Sister"
  description: "一位迷人的青年姐姐声音，韩语。"
  provider_data:
    voice_id: "Korean_EnchantingSister"
    voice_type: "system"
