---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Korean_PossessiveMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Possessive Man"
  description: "一位权威、占有欲强的中年男性声音，韩语。"
  provider_data:
    voice_id: "Korean_PossessiveMan"
    voice_type: "system"
