---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Korean_HaughtyLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Haughty Lady"
  description: "一位高傲冷漠的青年女士声音，韩语。"
  provider_data:
    voice_id: "Korean_HaughtyLady"
    voice_type: "system"
