---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Korean_ElegantPrincess"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Elegant Princess"
  description: "一位优雅的青年公主声音，韩语。"
  provider_data:
    voice_id: "Korean_ElegantPrincess"
    voice_type: "system"
