---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Korean_SassyGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Sassy Girl"
  description: "一位温柔的青年女性声音，韩语。"
  provider_data:
    voice_id: "Korean_SassyGirl"
    voice_type: "system"
    model: speech-2.6-turbo
