---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Korean_EnthusiasticTeen"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Enthusiastic Teen"
  description: "一位热情活泼的青年男性声音，韩语。"
  provider_data:
    voice_id: "Korean_EnthusiasticTeen"
    voice_type: "system"
