---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Korean_MysteriousGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Mysterious Girl"
  description: "一位灵动神秘的青年女孩声音，韩语。"
  provider_data:
    voice_id: "Korean_MysteriousGirl"
    voice_type: "system"
