---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Korean_ChildhoodFriendGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Childhood Friend Girl"
  description: "一位温柔的青梅竹马女孩声音，韩语。"
  provider_data:
    voice_id: "Korean_ChildhoodFriendGirl"
    voice_type: "system"
