---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Korean_MatureLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Mature Lady"
  description: "一位优雅成熟的中年女士声音，韩语。"
  provider_data:
    voice_id: "Korean_MatureLady"
    voice_type: "system"
