---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Korean_StrictBoss"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Strict Boss"
  description: "一位严厉的中年男性老板声音，韩语。"
  provider_data:
    voice_id: "Korean_StrictBoss"
    voice_type: "system"
