---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Korean_CharmingSister"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Charming Sister"
  description: "一位富有魅惑力的中年姐姐声音，韩语。"
  provider_data:
    voice_id: "Korean_CharmingSister"
    voice_type: "system"
    model: speech-2.6-turbo
