---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Korean_AthleticStudent"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Athletic Student"
  description: "一位充满活力的青年运动学生声音，韩语。"
  provider_data:
    voice_id: "Korean_AthleticStudent"
    voice_type: "system"
