---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Korean_ColdGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Cold Girl"
  description: "一位冷漠的青年女孩声音，韩语。"
  provider_data:
    voice_id: "Korean_ColdGirl"
    voice_type: "system"
