---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Korean_EnchantingSister"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Enchanting Sister"
  description: "一位迷人的青年姐姐声音，韩语。"
  provider_data:
    voice_id: "Korean_EnchantingSister"
    voice_type: "system"
    model: "speech-2.6-turbo"
