---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Korean_BraveAdventurer"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Brave Adventurer"
  description: "一位活泼勇敢的青年女冒险家声音，韩语。"
  provider_data:
    voice_id: "Korean_BraveAdventurer"
    voice_type: "system"
    model: "speech-2.6-turbo"
