---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Korean_CockyGuy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Cocky Guy"
  description: "一位调皮自大的青年男性声音，韩语。"
  provider_data:
    voice_id: "Korean_CockyGuy"
    voice_type: "system"
    model: "speech-2.6-turbo"
