---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Korean_ColdYoungMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Cold Young Man"
  description: "一位冷静的青年男性声音，韩语。"
  provider_data:
    voice_id: "Korean_ColdYoungMan"
    voice_type: "system"
