---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:lengdan_xiongzhang"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "冷淡学长"
  provider_data:
    voice_id: "lengdan_xiongzhang"
    voice_type: "system"
