---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:male-qn-daxuesheng-jingpin"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "青年大学生音色-beta"
  provider_data:
    voice_id: "male-qn-daxuesheng-jingpin"
    voice_type: "system"
