---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:male-qn-badao"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "霸道青年音色"
  provider_data:
    voice_id: "male-qn-badao"
    voice_type: "system"
