---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_AttractiveGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Attractive Girl"
  description: "一位迷人有魅力的青年女性声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_AttractiveGirl"
    voice_type: "system"
