---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_CaptivatingStoryteller"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Captivating Storyteller"
  description: "一位迷人的中年男性叙述者声音，非常适合讲故事，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_CaptivatingStoryteller"
    voice_type: "system"
    model: speech-2.6-turbo
