---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_ConfidentWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Confident Woman"
  description: "一位清晰坚定的自信青年女性声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_ConfidentWoman"
    voice_type: "system"
