---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Portuguese_GentleTeacher"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Gentle Teacher"
  description: "一位温和温柔的青年男性教师声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_GentleTeacher"
    voice_type: "system"
