---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_ThoughtfulMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Thoughtful Man"
  description: "一位温柔体贴的青年男性声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_ThoughtfulMan"
    voice_type: "system"
