---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_CharmingLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Charming Lady"
  description: "一位迷人的青年女性声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_CharmingLady"
    voice_type: "system"
    model: speech-2.6-turbo
