---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Portuguese_DeterminedManager"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Determined Manager"
  description: "一位自信果决的中年女性经理声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_DeterminedManager"
    voice_type: "system"
