---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Portuguese_SmartYoungGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Smart Young Girl"
  description: "一位聪慧的青年女孩声音，敏锐而清晰，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_SmartYoungGirl"
    voice_type: "system"
