---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_Debator"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Debator"
  description: "一位强硬的中年男性辩手声音，强壮而果断，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_Debator"
    voice_type: "system"
    model: speech-2.6-turbo
