---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_Ghost"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Ghost"
  description: "一位性感的青年男性鬼魂声音，神秘而诱人，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_Ghost"
    voice_type: "system"
    model: speech-2.6-turbo
