---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Portuguese_NaughtySchoolgirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Naughty Schoolgirl"
  description: "一位诱人顽皮的青年女学生声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_NaughtySchoolgirl"
    voice_type: "system"
