---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_SensibleManager"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Sensible Manager"
  description: "一位富有魅力、理智的中年男性经理声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_SensibleManager"
    voice_type: "system"
