---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_Grinch"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Grinch"
  description: "一位狡黠的青年男性格林奇式声音，淘气而狡猾，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_Grinch"
    voice_type: "system"
