---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_Deep-VoicedGentleman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Deep-voiced Gentleman"
  description: "一位声音低沉的青年绅士声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_Deep-VoicedGentleman"
    voice_type: "system"
