---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_GrimReaper"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Grim Reaper"
  description: "一位阴森的青年男性死神声音，黑暗而不祥，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_GrimReaper"
    voice_type: "system"
