---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_Kind-heartedGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Kind-hearted Girl"
  description: "一位平和善良的青年女性声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_Kind-heartedGirl"
    voice_type: "system"
