---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_SantaClaus"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Santa Claus"
  description: "一位欢乐的中年男性圣诞老人声音，充满节日气氛，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_SantaClaus"
    voice_type: "system"
    model: "speech-2.6-turbo"
