---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_CharmingQueen"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Charming Queen"
  description: "一位迷人有魅力的青年女王声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_CharmingQueen"
    voice_type: "system"
    model: speech-2.6-turbo
