---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Portuguese_EnergeticBoy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Energetic Boy"
  description: "一位活泼充满活力的青年男性声音，葡萄牙语。"
  provider_data:
    voice_id: "Portuguese_EnergeticBoy"
    voice_type: "system"
