---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:qiaopi_mengmei"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "俏皮萌妹"
  provider_data:
    voice_id: "qiaopi_mengmei"
    voice_type: "system"
