---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:qiaopi_mengmei"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "俏皮萌妹"
  provider_data:
    voice_id: "qiaopi_mengmei"
    voice_type: "system"
    model: speech-2.6-turbo
