---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Russian_CrazyQueen"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Crazy Girl"
  description: "一位充满活力的青年“疯狂女孩”声音，狂野而不可预测，俄语。"
  provider_data:
    voice_id: "Russian_CrazyQueen"
    voice_type: "system"
