---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Russian_Bad-temperedBoy"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Bad-tempered Boy"
  description: "一位脾气暴躁的青年男性声音，俄语。"
  provider_data:
    voice_id: "Russian_Bad-temperedBoy"
    voice_type: "system"
    model: "speech-2.6-turbo"
