---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Russian_ReliableMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Reliable Man"
  description: "一位稳重可靠的中年男性声音，俄语。"
  provider_data:
    voice_id: "Russian_ReliableMan"
    voice_type: "system"
