---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Russian_AmbitiousWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Ambitious Woman"
  description: "一位强势、雄心勃勃的青年女性声音，俄语。"
  provider_data:
    voice_id: "Russian_AmbitiousWoman"
    voice_type: "system"
