---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Russian_BrightHeroine"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Bright Queen"
  description: "一位傲慢明艳的青年女王声音，俄语。"
  provider_data:
    voice_id: "Russian_BrightHeroine"
    voice_type: "system"
