---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Russian_HandsomeChildhoodFriend"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Handsome Childhood Friend"
  description: "一位为英俊青梅竹马角色设计的迷人少女声音，俄语。"
  provider_data:
    voice_id: "Russian_HandsomeChildhoodFriend"
    voice_type: "system"
