---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Santa_Claus"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Santa Claus"
  provider_data:
    voice_id: "Santa_Claus"
    voice_type: "system"
