---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Spanish_WhimsicalGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Whimsical Girl"
  description: "一位机智、奇特的青年女性声音，西班牙语。"
  provider_data:
    voice_id: "Spanish_WhimsicalGirl"
    voice_type: "system"
