---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Spanish_BossyLeader"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Bossy Leader"
  description: "一位干练、专横的青年男性领导者声音，西班牙语。"
  provider_data:
    voice_id: "Spanish_BossyLeader"
    voice_type: "system"
    model: speech-2.6-turbo
