---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Spanish_Kind-heartedGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Kind-hearted Girl"
  description: "一位明亮善良的青年女性声音，西班牙语。"
  provider_data:
    voice_id: "Spanish_Kind-heartedGirl"
    voice_type: "system"
