---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Spanish_CompellingGirl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Compelling Girl"
  description: "一位富有说服力、引人注目的青年女性声音，西班牙语。"
  provider_data:
    voice_id: "Spanish_CompellingGirl"
    voice_type: "system"
