---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Spanish_AngryMan"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Angry Man"
  description: "一位语气激烈的青年男性声音，传达愤怒，西班牙语。"
  provider_data:
    voice_id: "Spanish_AngryMan"
    voice_type: "system"
