---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Spanish_FrankLady"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Frank Lady"
  description: "一位激动、坦率的青年女士声音，西班牙语。"
  provider_data:
    voice_id: "Spanish_FrankLady"
    voice_type: "system"
