---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Spanish_Ghost"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Ghost"
  description: "一位沙哑的青年男性鬼魂声音，西班牙语。"
  provider_data:
    voice_id: "Spanish_Ghost"
    voice_type: "system"
