---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Spanish_PowerfulSoldier"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Powerful Soldier"
  description: "一位年轻有力的青年男性强大士兵声音，西班牙语。"
  provider_data:
    voice_id: "Spanish_PowerfulSoldier"
    voice_type: "system"
