---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "minimax-tenant:minimax-cn:Spanish_CaringGirlfriend"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    name: "minimax-cn"
  name: "Caring Girlfriend"
  description: "一位梦幻般的青年女性关怀女友声音，西班牙语。"
  provider_data:
    voice_id: "Spanish_CaringGirlfriend"
    voice_type: "system"
