---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Spanish_Rudolph"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Rudolph"
  description: "一位天真的青年男性声音，鲁道夫风格，西班牙语。"
  provider_data:
    voice_id: "Spanish_Rudolph"
    voice_type: "system"
    model: speech-2.6-turbo
