---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Sweet_Girl"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Sweet Girl"
  provider_data:
    voice_id: "Sweet_Girl"
    voice_type: "system"
