---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:tianxin_xiaoling"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "甜心小玲"
  provider_data:
    voice_id: "tianxin_xiaoling"
    voice_type: "system"
    model: speech-2.6-turbo
