---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Turkish_CalmWoman"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Calm Woman"
  description: "一位宁静的青年女性土耳其语声音，非常适合有声读物。"
  provider_data:
    voice_id: "Turkish_CalmWoman"
    voice_type: "system"
    model: speech-2.6-turbo
