---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "minimax-tenant:minimax-cn:Ukrainian_WiseScholar"
spec:
  source: manual
  provider:
    kind: "minimax-tenant"
    id: "minimax-cn"
  display_name: "Wise Scholar"
  description: "一位亲切健谈的青年男性智慧学者声音，乌克兰语。"
  provider_data:
    voice_id: "Ukrainian_WiseScholar"
    voice_type: "system"
    model: "speech-2.6-turbo"
