---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "volc-tenant:volc-cn-beijing:en_female_female_tutor_ms-jenny_uranus_bigtts"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    id: "volc-cn-beijing"
  display_name: "Holly 2.0"
  description: "Provider restriction: Context mode only."
  provider_data:
    resource_id: "seed-tts-2.0"
    voice_id: "en_female_female_tutor_ms-jenny_uranus_bigtts"
