---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "volc-tenant:volc-cn-beijing:en_female_lana_del_rey_kelley_d_p1_uranus_bigtts"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    id: "volc-cn-beijing"
  display_name: "Lynn 2.0"
  provider_data:
    resource_id: "seed-tts-2.0"
    voice_id: "en_female_lana_del_rey_kelley_d_p1_uranus_bigtts"
