---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "volc-tenant:volc-cn-beijing:en_male_glen_emo_v2_mars_bigtts"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    name: "volc-cn-beijing"
  name: "Glen"
  provider_data:
    resource_id: "seed-tts-1.0"
    voice_id: "en_male_glen_emo_v2_mars_bigtts"
