---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "volc-tenant:volc-cn-beijing:ICL_zh_male_xuebanantongzhuo_tob"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    id: "volc-cn-beijing"
  display_name: "学霸男同桌"
  provider_data:
    resource_id: "seed-tts-1.0"
    voice_id: "ICL_zh_male_xuebanantongzhuo_tob"
