---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "volc-tenant:volc-cn-beijing:ICL_en_female_cc_cm_v1_tob"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    name: "volc-cn-beijing"
  name: "Charlie"
  provider_data:
    resource_id: "seed-tts-1.0"
    voice_id: "ICL_en_female_cc_cm_v1_tob"
