---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "volc-tenant:volc-cn-beijing:ICL_en_male_michael_tob"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    name: "volc-cn-beijing"
  name: "Michael"
  provider_data:
    resource_id: "seed-tts-1.0"
    voice_id: "ICL_en_male_michael_tob"
