---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "volc-tenant:volc-cn-beijing:ICL_zh_male_renyuwangzi_v1_tob"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    id: "volc-cn-beijing"
  display_name: "清朗温润"
  provider_data:
    resource_id: "seed-tts-1.0"
    voice_id: "ICL_zh_male_renyuwangzi_v1_tob"
