---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "volc-tenant:volc-cn-beijing:ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    name: "volc-cn-beijing"
  name: "黯刃秦主"
  provider_data:
    resource_id: "seed-tts-1.0"
    voice_id: "ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob"
