---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "volc-tenant:volc-cn-beijing:ICL_zh_female_guaiqiaokeer_cs_tob"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    name: "volc-cn-beijing"
  name: "乖巧可儿"
  provider_data:
    resource_id: "seed-tts-1.0"
    voice_id: "ICL_zh_female_guaiqiaokeer_cs_tob"
