---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "volc-tenant:volc-cn-beijing:id_male_bv164dialogue_uranus_bigtts"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    id: "volc-cn-beijing"
  display_name: "Elian 2.0"
  provider_data:
    resource_id: "seed-tts-2.0"
    voice_id: "id_male_bv164dialogue_uranus_bigtts"
