---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "volc-tenant:volc-cn-beijing:ko_female_bv546_uranus_bigtts"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    id: "volc-cn-beijing"
  display_name: "Momo 2.0"
  provider_data:
    resource_id: "seed-tts-2.0"
    voice_id: "ko_female_bv546_uranus_bigtts"
