---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "volc-tenant:volc-cn-beijing:multi_male_jingqiangkanye_moon_bigtts"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    name: "volc-cn-beijing"
  name: "かずね（和音）"
  provider_data:
    resource_id: "seed-tts-1.0"
    voice_id: "multi_male_jingqiangkanye_moon_bigtts"
