---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  name: "volc-tenant:volc-cn-beijing:zh_female_tianmeixiaoyuan_moon_bigtts"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    name: "volc-cn-beijing"
  name: "甜美小源"
  provider_data:
    resource_id: "seed-tts-1.0"
    voice_id: "zh_female_tianmeixiaoyuan_moon_bigtts"
