---
apiVersion: gizclaw.admin/v1alpha1
kind: Voice
metadata:
  id: "volc-tenant:volc-cn-beijing:zh_male_yangguangqingnian_mars_bigtts"
spec:
  source: manual
  provider:
    kind: "volc-tenant"
    id: "volc-cn-beijing"
  display_name: "活力小哥"
  provider_data:
    resource_id: "seed-tts-1.0"
    voice_id: "zh_male_yangguangqingnian_mars_bigtts"
