---
apiVersion: gizclaw.admin/v1alpha1
kind: VolcTenant
metadata:
  name: volc-cn-beijing
spec:
  credential_name: volc-credential
  description: Volc/Doubao tenant in CN Beijing
  region: cn-beijing
  resource_ids:
    - seed-tts-1.0
    - seed-tts-2.0
    - seed-icl-1.0
    - seed-icl-2.0
    - volc.bigasr.sauc.duration
    - volc.speech.dialog
    - volc.service_type.10053
